EyeSeeTea/pictureapp

- app/src/main/assets/Questions.csv
- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Tab.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- DynamicTabAdapter (based on AutoTabAdapter) with no scores at all
- Parent-Child questions issued solved.
Now the survey can be fulfilled.
> Remove scores

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
Applies malariaapp changes (dashboard) to pictureapp
> Solves dashboard refresh error

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/res/drawable/background_dynamic_clicked_option.xml
- app/src/main/res/layout/dynamic_tab_row_singleitem.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values/strings.xml
> Graphics survey layout

- app/src/main/AndroidManifest.xml
- app/src/main/assets/Options.csv
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Value.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/receivers/AlarmPushReceiver.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
Refresh dashboard issue when automatic push is running in background is not implemented yet.
> Automatic push

- app/build.gradle
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values/strings.xml
Tested in API 25 and API 16.
Added button in settings to remove all sent results.
> New button ‘Remove all sent results’

- app/src/main/res/xml/pref_general.xml
I forgot commit and push the changes of the file  with the Shared Preferents.
> Button remove all sent results

- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
- app/src/main/java/org/eyeseetea/malariacare/views/AutoCompleteEditTextPreference.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values/strings.xml
Added:
Patch the description.
Change url to check the program id.
Check if the program exist.
> Ban abusive organitation unit

- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
- app/src/main/java/org/eyeseetea/malariacare/views/AutoCompleteEditTextPreference.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values/strings.xml
Reverts EyeSeeTea/pictureapp#99
> Revert "Ban abusive organitation unit"

- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
- app/src/main/java/org/eyeseetea/malariacare/views/AutoCompleteEditTextPreference.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values/strings.xml
Added Settings check of the valid org_units.
Add ou description when closing ou #93 
Change warning texts #96 
Verify the org unit is active for the program #94
(Ban abusive organitation unit #99)
> Ban abusive org unit new features

- app/src/main/AndroidManifest.xml
Look the [issue comment](https://github.com/EyeSeeTea/pictureapp/issues/106#issuecomment-149846156)
> Fixed the user-permissions

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/views/AutoCompleteEditTextPreference.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
Now Checks wrong server url, only one time(for invalid value in start url value), or in every change of url server.
And reload the org_units when the server url is changed:
I added extra condition, with one more android permission:
Checks if the mobile has Internet access
> Urlserver check and reload

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/views/AutoCompleteEditTextPreference.java
- app/src/main/java/org/eyeseetea/malariacare/views/filters/AutocompleteAdapterFilter.java
- app/src/main/res/layout/dynamic_tab_grid_question.xml
- app/src/main/res/menu/menu_general.xml
- app/src/main/res/xml/pref_general.xml
-Center the title of the question
-Remove logout button from preference menu
-OU search (for autocomplete) should search at any position (not just at the beginning)
> Filter autocomplete, center title, remove logout button, and change some values

- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
The application counts how many surveys Have Been created in the same hour for each of the surveys between 0 and 1 hours.
> Change ban organization logic

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/views/AutoCompleteEditTextPreference.java
Sorry @adrianq 
I detected and fixed some bugs in my last pull requests.
Fixed:
-Remove incomplete surveys not working properly. Its fixed and works now, but its a temporarily fix.
-The OU default = " " did slower the application. Its fixed. 
-I added a condition and i dont check ok(i thought yes but not), it block next attempts to conexion. Its fixed.
> Fix bug survey progress and empty org_unit

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/views/Dialog.java
- app/src/main/res/raw-es/about.txt
- app/src/main/res/raw-fr/about.txt
- app/src/main/res/raw/about.txt
@adrianq i copy the structure of malariapp 
I found a bug, if you press the link mailito the aplication crash. I think It needs be called in a Intent
> About us text

- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
- app/src/main/java/org/eyeseetea/malariacare/views/AutoCompleteEditTextPreference.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
i did the changes and I tested in the production server.
(pull org units push survey negative positive check values...).
I have not tried to be banned in the production server because I can not access the web interface to remove the ban.
I only tried it in dev server for check the new string.
I found two bugs(the first load the org_unit is not loaded, and the first org_unit is not showed)
it was fixed.
Do not forget: put the correct user and password.
> Change strings and server

- app/src/main/res/raw-es/about.txt
- app/src/main/res/raw-fr/about.txt
- app/src/main/res/raw/about.txt
> License txt

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Value.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/MonitorRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/ASMQRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/CounterRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/DHAPIP1RowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/DHAPIP2RowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/DHAPIP3RowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/NegativeRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/NotTestedRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/PeriodRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/PfPvRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/PfRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/PositiveRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/PositivityRateRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/PvRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/RDTRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/ReferralRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/SuspectedRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/utils/SurveyMonitor.java
- app/src/main/java/org/eyeseetea/malariacare/services/MonitorService.java
> Substitutes querys for values  with loops (optimization)

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/res/layout/assessment_header.xml
- app/src/main/res/layout/assessment_record.xml
- app/src/main/res/layout/assessment_sent_header.xml
- app/src/main/res/layout/assessment_sent_record.xml
- app/src/main/res/values/dimens.xml
> Dashboard with more spacing, greater font size

- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
> pull OUs after Eula is accepted

- app/src/main/java/org/eyeseetea/malariacare/MonitorActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
- app/src/main/res/layout/fragment_dashboard.xml
- app/src/main/res/values/donottranslate.xml
> Bug crash on list out of screen

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/MonitorRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/utils/TimePeriodCalculator.java
Closes  #187
and closes #185 
Added: 
wipe of the sdk db before pull(like in malariapp).
Fixed:
-discard surveys with date after the present date.
-fix day key to show the day by month
> Bug suspected cases apparently wrong

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values/strings.xml
> Feature content new translations

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Feature add time controldataelement push without uids

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
> Fix Sent/unsent inverted

- app/src/main/java/org/eyeseetea/malariacare/monitor/utils/SurveyMonitor.java
> Fix bug in monitor stats: susspected blank surveys

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> fix surveys order list

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
> fix bug pulling events

- app/src/main/res/values-km/strings.xml
> Fix khmer translation of dha-pip

- app/src/main/res/values-km/strings.xml
> Added sent-unsent-monitoring khmer translations

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> Fix hide keyboard

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/res/values/donottranslate.xml
> Bug fix info

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ReadWriteDB.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> Bug fix remove old values

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
Its only remove the last ", " in the info column
> Remove final ", "

- app/build.gradle
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/res/layout/tab_dashboard.xml
- build.gradle
> Feature hide tabhost

- app/src/main/assets/Questions.csv
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration2AddQuestionColumn.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration3AddQuestionColumn.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/ReadWriteDB.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationController.java
> Feature show question number

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
> Back button from sent survey go to sent fragment

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> fix review pagination

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> Fixed keyboard Ok in number and phone input

- app/src/main/java/org/eyeseetea/malariacare/monitor/rows/PositivityRateRowBuilder.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/utils/SurveyMonitor.java
> Fix posibility stats don't use not tested cases

- app/src/main/assets/Questions.csv
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration4AddQuestionVisibleColumn.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
> Feature hidden options in info

- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PreferencesState.java
> make pull use directly the server configured in login screen

- app/src/main/res/values-km/strings.xml
> Modify referall string

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/models/EventExtended.java
Closes #278
@ifoche It works for my in the first try. maybe i missing something?
For example the event: https://dev.psi-mis.org/api/events/h81VkWjSVDm
In the web the date is shown with american format.
> Send the Date and time in the event Timecapture and Time Sent

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> Show review option always

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
> Fix bug removing delete inprogress surveys on restart

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
> removed app_name_local and used app_name instead

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
> Bug fix unsent date

- app/src/main/java/org/eyeseetea/malariacare/monitor/utils/SurveyMonitor.java
> Fixed pf / pfpv ids

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationController.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
> Fix 317 blanks

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/network/ServerAPIController.java
- app/src/main/java/org/eyeseetea/malariacare/receivers/AlarmPushReceiver.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
> Alarm cancel in background, sdk data wiped PushService onDestroy

- app/src/main/res/layout/dynamic_tab_row.xml
- app/src/main/res/layout/dynamic_tab_row_singleitem.xml
> Fix - scale question image size

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> Bug prevent multiple clicks in buttons

- app/src/laos/res/raw/licenses.txt
- app/src/main/res/raw/licenses.txt
> Added boon lao/thai font license

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
> Remove cancelAlarm from DashboardActivity and exit on SettingsActivity

- app/src/cambodia/res/values/colors.xml
- app/src/laos/assets/Questions.csv
- app/src/laos/res/values/colors.xml
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration7AddQuestionPathAttributeColumn.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/res/layout/dynamic_tab_grid_question.xml
> Feature optional question image

- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
> Increase populate performance

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
> Feature remove counter value on recursive delete

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
> Fix num required questions

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
> Fix bug, get survey from query not from session on reloadAnswered

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
> Feature import conflict survey without value conflict

- app/src/laos/res/layout/dynamic_tab_phone_row.xml
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/res/layout/dynamic_tab_grid_question.xml
- app/src/main/res/layout/dynamic_tab_row_question_image.xml
> fix dialog screen resize

- app/src/laos/assets/monitor/monitor.html
- app/src/main/res/layout/dynamic_review_row.xml
> Bug review lao values doesnt shown

- app/src/laos/assets/Questions.csv
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
-[x] Fix pagination total questions.
-[x] Hide pagination in Warning/reminder/counter screens
Closes #392
> Bug modify totalquestions pagination

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
> Add go to left in reviewfragment when the user pressback

- app/src/cambodia/res/values-es/strings.xml
- app/src/cambodia/res/values-fr/strings.xml
- app/src/cambodia/res/values-km/strings.xml
- app/src/laos/res/values-es/strings.xml
- app/src/laos/res/values-fr/strings.xml
- app/src/laos/res/values-km/strings.xml
- app/src/laos/res/values-lo/strings.xml
- app/src/laos/res/values-th/strings.xml
- app/src/laos/res/values/strings.xml
Closes #403
@ifoche  i fixed the PSI number to(in lao and cambodia)... Only the english string had the correct phone.
> Feature change psk to psi strings

- app/src/laos/java/utils/PhoneMask.java
Closes #402
Exclude 020|030 in xxx xxx xxx mask.
And added ^ $ to encapsulate the regexpr.
> Exclude the 020 and 030 from the (xxx) xxx-xxx mask

- app/src/cambodia/java/org/eyeseetea/malariacare/layout/SurveyInfoUtils.java
- app/src/laos/assets/Questions.csv
- app/src/laos/java/org/eyeseetea/malariacare/layout/SurveyInfoUtils.java
- app/src/laos/res/values-es/strings.xml
- app/src/laos/res/values-fr/strings.xml
- app/src/laos/res/values-km/strings.xml
- app/src/laos/res/values-lo/strings.xml
- app/src/laos/res/values-th/strings.xml
- app/src/laos/res/values/strings.xml
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/AAssessmentAdapter.java
- app/src/main/res/values/donottranslate.xml
> Feature modify survey info

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
Closes #405
I removed unused method, and a survey sets as sent only when was sent like in malariaapp
> Set as sent only if the survey send was finish(like in malariapp).

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/ReviewFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> Feature review fragment changes

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> Truncate the 00-09 values as integer(0-9)

- app/src/cambodia/java/org/eyeseetea/malariacare/monitor/utils/SurveyMonitor.java
- app/src/laos/java/org/eyeseetea/malariacare/monitor/utils/SurveyMonitor.java
- app/src/main/java/org/eyeseetea/malariacare/monitor/utils/BaseSurveyMonitor.java
> Monitoring Question ids and options ids names refactor

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
> Send the completion date as event.eventdate

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
Closes #178
I added  the default value in malaria app to limit the events by date( 6 months)
> Added pull of events with startDate

- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
Closes #482
(needs the sdk update)
> Fix short pull

- app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Tab.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
> Fix navigation builder to init in a multiquestiontab and without single

- app/src/cambodia/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
- app/src/cambodia/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
- app/src/laos/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
- app/src/laos/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/Credentials.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/PushSurveysUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/PushUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
- app/src/main/java/org/eyeseetea/malariacare/services/strategies/APushServiceStrategy.java
- app/src/myanmar/java/org/eyeseetea/malariacare/domain/usecase/LoadUserAndCredentialsUseCase.java
- app/src/myanmar/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
- app/src/myanmar/java/org/eyeseetea/malariacare/domain/usecase/MockedPushSurveysUseCase.java
- app/src/myanmar/java/org/eyeseetea/malariacare/domain/usecase/PushMockUseCase.java
- app/src/myanmar/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
- app/src/myanmar/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
> Feature mockup surveys push process

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Permissions.java
> Feature user permissions

- app/src/main/java/org/eyeseetea/malariacare/network/ServerAPIController.java
- app/src/main/java/org/eyeseetea/malariacare/views/AutoCompleteEditTextPreference.java
> Bug ban org units

- app/src/laos/res/values-lo/paths.xml
> Fix lao image path

- app/src/cambodia/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
- app/src/laos/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
- app/src/main/java/org/eyeseetea/malariacare/layout/utils/BaseLayoutUtils.java
> Bug restore old actionbar

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
Closes #535 
- All the tab names was wrong in all the variants.
- I removed unused variables and code from malariapp.
> Bug tab names

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/database/model/Answer.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/myanmar/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
- app/src/myanmar/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
> Feature orgunits as options in demo mode

- app/src/cambodia/java/org/eyeseetea/malariacare/domain/usecase/HeaderUseCase.java
- app/src/laos/java/org/eyeseetea/malariacare/domain/usecase/HeaderUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardUnsentFragment.java
> fix PR bugs

- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/res/layout/survey.xml
- gradle.properties
> show ProgressBar while creating NavigationController

- app/src/myanmar/res/values-my/strings.xml
- app/src/myanmar/res/values-zh/strings.xml
- app/src/myanmar/res/values/strings.xml
> Added "is a example" in treatment question in myanmar

- app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/views/CustomRadioButton.java
- app/src/myanmar/res/values/strings.xml
> Feature modify within text

- app/src/myanmar/java/org/eyeseetea/malariacare/monitor/utils/SurveyMonitor.java
> total tested in monitoring should not count invalids

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/general/OptionArrayAdapter.java
> Added custom params in OptionArrayAdapter

- app/src/myanmar/java/utils/PhoneMask.java
- app/src/myanmar/res/values-my/strings.xml
- app/src/myanmar/res/values-zh/strings.xml
- app/src/myanmar/res/values/strings.xml
> Added phoneMask (plain text between 7 and 15 digits) in myanmar

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/QuestionCounter.java
- app/src/myanmar/java/org/eyeseetea/malariacare/views/question/singlequestion/strategies/ConfirmCounterSingleCustomViewStrategy.java
> Bug compulsory ignored on massive clicks

- app/src/main/java/org/eyeseetea/malariacare/layout/listeners/SwipeTouchListener.java
> Bug scroll jump top

- app/src/laos/java/org/eyeseetea/malariacare/database/PostMigration.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration21LaoNewRelation.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
> Added new lao relations

- app/src/cambodia/java/org/eyeseetea/malariacare/domain/usecase/ReviewUseCase.java
- app/src/laos/java/org/eyeseetea/malariacare/domain/usecase/ReviewUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/ReviewScreenAdapter.java
- app/src/myanmar/java/org/eyeseetea/malariacare/domain/usecase/ReviewUseCase.java
- app/src/myanmar/res/layout/dynamic_tab_row_empty_question.xml
> Bug missing resource

- app/src/laos/java/org/eyeseetea/malariacare/strategies/ReviewFragmentStrategy.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/res/layout/dynamic_bottom_view.xml
- app/src/main/res/layout/no_scrolled_table.xml
- app/src/main/res/layout/options_table.xml
- app/src/main/res/layout/scrolled_table.xml
> Bug missing resources questions and swipe after merge

- app/src/cambodia/java/org/eyeseetea/malariacare/database/PostMigration.java
- app/src/laos/java/org/eyeseetea/malariacare/database/PostMigration.java
- app/src/main/java/org/eyeseetea/malariacare/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/database/migrations/Migration22ModifyValuesLastMigration.java
- app/src/main/java/org/eyeseetea/malariacare/database/utils/PopulateDB.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/Phone.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/PositiveNumber.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/PositiveOrZeroNumber.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/Validation.java
- app/src/main/java/org/eyeseetea/malariacare/domain/exception/InvalidPositiveOrZeroNumberException.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/presentation/factory/MultiQuestionViewFactory.java
- app/src/main/java/org/eyeseetea/malariacare/presentation/factory/SingleQuestionViewFactory.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/NumberMultiQuestionView.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/PhoneMultiQuestionView.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/PositiveNumberMultiQuestionView.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/PositiveOrZeroNumberMultiQuestionView.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/singlequestion/PhoneSingleQuestionView.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/singlequestion/PositiveNumberSingleQuestionView.java
- app/src/main/res/layout/scrolled_table.xml
- app/src/myanmar/assets/Questions.csv
- app/src/myanmar/java/org/eyeseetea/malariacare/database/PostMigration.java
- app/src/test/java/org/eyeseetea/malariacare/domain/entity/PositiveOrZeroNumberTest.java
- app/src/test/java/org/eyeseetea/malariacare/domain/entity/ValidationTest.java
> Feature myanmar feedback

- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/PullDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/PullController.java
- app/src/myanmar/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
closes #717 
SDK Branch https://github.com/EyeSeeTea/dhis2-android-sdk/tree/2.25_feature_download_user_attributes
> download attributes in metadata pull process

- app/src/main/java/org/eyeseetea/malariacare/data/remote/PullDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/PullController.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/models/ProgramExtended.java
closes #716 
This feature needs the sdk branch: [EyeSeeTea_refactor_create_event_filters_object](https://github.com/EyeSeeTea/dhis2-android-sdk/tree/2.25-EyeSeeTea_refactor_create_event_filters_object)
> Feature add data pull of server to the pull process

- app/src/myanmar/java/org/eyeseetea/malariacare/presentation/factory/stock/tables/StockTableBuilder.java
> Hide status line in stock table.

- app/src/cambodia/java/org/eyeseetea/malariacare/data/remote/strategies/PullDhisSDKDataSourceStrategy.java
- app/src/laos/java/org/eyeseetea/malariacare/data/remote/strategies/PullDhisSDKDataSourceStrategy.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/PullDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/remote/strategies/IPullDhisSDKDataSourceStrategy.java
- app/src/myanmar/java/org/eyeseetea/malariacare/data/remote/strategies/PullDhisSDKDataSourceStrategy.java
closes #797 
this PR required this branch of dhis sdk https://github.com/EyeSeeTea/dhis2-android-sdk/tree/feature_change_on_volunteer_user_attribute_logic
> Feature change on volunteer user attribute logic

- app/src/myanmar/res/layout/snackbar.xml
> Put margin to right button of snackbar

- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/models/DataValueExtended.java
> Bug problems with quarantine and push

- app/src/myanmar/res/layout/assessment_record.xml
> Put wrap content to sent and unsent lines instead of put the weight

- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
> Bug available table not showing correct value

- app/src/myanmar/java/org/eyeseetea/malariacare/data/remote/strategies/PullDhisSDKDataSourceStrategy.java
> Remove duplicate pull

- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/models/DataValueExtended.java
- app/src/myanmar/java/org/eyeseetea/malariacare/data/sync/importer/strategies/DataConverterStrategy.java
> Prevent null on blank old surveys

- app/src/myanmar/res/values/donottranslate.xml
> Put default url https://dev.scpr-mm-mal.org

- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
> Fix survey lists

- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
- app/src/myanmar/java/org/eyeseetea/malariacare/fragments/NewReceiptBalanceFragment.java
> Feature today new receipt balance

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/Treatment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/ReviewFragment.java
- app/src/myanmar/java/org/eyeseetea/malariacare/domain/usecase/MockedPushSurveysUseCase.java
- app/src/myanmar/java/org/eyeseetea/malariacare/layout/adapters/dashboard/strategies/DashboardAdapterStrategy.java
- app/src/myanmar/java/org/eyeseetea/malariacare/layout/adapters/survey/strategies/DynamicTabAdapterStrategy.java
- app/src/myanmar/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> Bug stock and malaria relation

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/Session.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> Fix crash on survey load

- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/Treatment.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/NumberRadioButtonMultiquestionView.java
> Bug null exception on change total question value question null

- app/src/main/java/org/eyeseetea/malariacare/domain/entity/Treatment.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/NumberRadioButtonMultiquestionView.java
- app/src/myanmar/res/values/donottranslate.xml
> Bug showing alternative act on cq

- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/ConvertFromSDKVisitor.java
> organisation user not in database

- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/populatedb/PopulateDB.java
> Remove OrgUnitlevel from mandatory tables

- app/src/main/java/org/eyeseetea/malariacare/data/database/datasources/AuthenticationLocalDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/PullController.java
- app/src/myanmar/assets/Organisations.csv
- app/src/myanmar/res/values/donottranslate.xml
> Adding test organisation if demo user logged

- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
- app/src/myanmar/res/values-my/strings.xml
- app/src/myanmar/res/values-zh/strings.xml
- app/src/myanmar/res/values/strings.xml
> add translation for really exit dialog

- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/LocationMemory.java
> Send default Location if latitude and longitude equals  to zero.

- app/src/cambodia/res/values/donottranslate.xml
- app/src/laos/res/values/donottranslate.xml
- app/src/main/res/values/donottranslate.xml
- app/src/myanmar/res/values/donottranslate.xml
> Put different default location for every variant.

- app/src/myanmar/res/layout/fragment_new_receipt_balance.xml
> Increase new receipt and new reset  drugs title width to fit burmese titles.

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SplashScreenActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/views/FontUtils.java
Closes #936 
@ifoche  This PR try to prevent the scale random crash and moves the  Crashlytics init to the first action in the application.
> Prevent scale crash

- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Question.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationBuilder.java
- app/src/main/res/layout/survey.xml
- app/src/myanmar/res/values-my/strings.xml
- app/src/myanmar/res/values-zh/strings.xml
- app/src/myanmar/res/values/strings.xml
Closes #953 
I did try to do it using the percentage based on the node position in the navigationBuilder from the active node, but the question nodes are called many times and it doesn't work.
Finally I created a list of fake messages, and the UI message is updated  when the active node in the navigation builder is the question in the middle of all the questions.
> Create fake progressBarText on SurveyFragment

- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Organisation.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/User.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/ConvertFromSDKVisitor.java
- app/src/myanmar/res/values/donottranslate.xml
> Added matrix as default category option

- app/src/myanmar/res/layout/fragment_new_receipt_balance.xml
- app/src/myanmar/res/values/colors.xml
> Put lighter edit texts hint color.

- app/src/main/java/org/eyeseetea/malariacare/SplashScreenActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/AppDatabase.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/migrations/Migration2ChangeTravelQuestionIcon.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/populatedb/PopulateDB.java
- app/src/myanmar/assets/Questions.csv
- app/src/myanmar/java/org/eyeseetea/malariacare/data/database/PostMigration.java
- app/src/myanmar/res/layout/multi_question_tab_dropdown_row.xml
> Cosmetics icon travel change

- app/src/cambodia/res/values-es/strings.xml
- app/src/cambodia/res/values-fr/strings.xml
- app/src/cambodia/res/values-km/strings.xml
- app/src/cambodia/res/values/strings.xml
- app/src/ereferrals/res/values-my/strings.xml
- app/src/ereferrals/res/values-zh/strings.xml
- app/src/ereferrals/res/values/strings.xml
- app/src/laos/res/values-es/strings.xml
- app/src/laos/res/values-fr/strings.xml
- app/src/laos/res/values-km/strings.xml
- app/src/laos/res/values-lo/strings.xml
- app/src/laos/res/values-th/strings.xml
- app/src/laos/res/values/strings.xml
> Bug missing string

- app/src/cambodia/java/org/eyeseetea/malariacare/data/sync/importer/strategies/ConvertFromSDKVisitorStrategy.java
- app/src/laos/java/org/eyeseetea/malariacare/data/sync/importer/strategies/ConvertFromSDKVisitorStrategy.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/importer/ConvertFromSDKVisitor.java
- app/src/myanmar/java/org/eyeseetea/malariacare/data/sync/importer/strategies/ConvertFromSDKVisitorStrategy.java
> Bug refactor myanmar categoryoptionuid

- app/src/cambodia/assets/Questions.csv
- app/src/cambodia/res/layout/dynamic_tab_pregnant_month_row.xml
- app/src/cambodia/res/values-km/strings.xml
- app/src/cambodia/res/values/strings.xml
- app/src/ereferrals/res/values-my/strings.xml
- app/src/ereferrals/res/values-zh/strings.xml
- app/src/ereferrals/res/values/strings.xml
- app/src/laos/res/values-lo/strings.xml
- app/src/laos/res/values/strings.xml
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/PregnantMonthNumber.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/Validation.java
- app/src/main/java/org/eyeseetea/malariacare/domain/exception/InvalidPregnantMonthNumberException.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/presentation/factory/MultiQuestionViewFactory.java
- app/src/main/java/org/eyeseetea/malariacare/presentation/factory/SingleQuestionViewFactory.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/PregnantMonthNumberMultiQuestionView.java
- app/src/main/java/org/eyeseetea/malariacare/views/question/singlequestion/PregnantMonthNumberSingleQuestionView.java
- app/src/main/res/layout/multi_question_tab_pregnant_month_int_row.xml
- app/src/main/res/layout/pregnant_month_int_item.xml
- app/src/myanmar/res/values-my/strings.xml
- app/src/myanmar/res/values-zh/strings.xml
- app/src/myanmar/res/values/strings.xml
> Added new pregnant int question

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
> go to first question when DynamicTabAdapter is initialized

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> evolve gradle to next version

- app/src/cambodia/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
- app/src/laos/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
> Added isLogged control to the lao/cambodia push

- app/src/main/java/org/eyeseetea/malariacare/fragments/SurveyFragment.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationBuilder.java
> fix navigation build exception if dashboard is not loaded and add log

- app/src/cambodia/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
- app/src/cambodia/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
- app/src/cambodia/res/values-km/strings.xml
- app/src/cambodia/res/values/strings.xml
- app/src/ereferrals/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
- app/src/ereferrals/res/values-my/strings.xml
- app/src/ereferrals/res/values-zh/strings.xml
- app/src/ereferrals/res/values/strings.xml
- app/src/laos/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
- app/src/laos/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
- app/src/laos/res/values-lo/strings.xml
- app/src/laos/res/values/strings.xml
- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/ALoginUseCase.java
- app/src/myanmar/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
- app/src/myanmar/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
- app/src/myanmar/res/values-my/strings.xml
- app/src/myanmar/res/values-zh/strings.xml
- app/src/myanmar/res/values/strings.xml
> Feature handle unexpected exceptions in login usecase

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
Closes https://github.com/EyeSeeTea/malariapp/issues/1413
> Fix export data on gmail bug

- app/src/main/java/org/eyeseetea/malariacare/network/SurveyChecker.java
> fix quarantine

- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
> set sending  surveys as quarantine on start

- app/src/laos/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> Solve bug with null orgunit in surveyPush

- app/src/main/java/org/eyeseetea/malariacare/presentation/factory/monitor/utils/TimePeriodCalculator.java
> Fix monitoring week and day

- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/DateFilter.java
- app/src/test/java/org/eyeseetea/malariacare/domain/entity/DateFilterTest.java
> Fix this month filter and test

- app/src/cambodia/java/org/eyeseetea/malariacare/strategies/ReviewFragmentStrategy.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/strategies/AReviewFragmentStrategy.java
> Show reviewScreen in not tested or negative test in cambodia

- app/src/laos/res/xml/pref_general.xml
> Show developer options

- app/src/main/java/org/eyeseetea/malariacare/data/remote/PushDhisSDKDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/sync/exporter/PushController.java
- app/src/main/java/org/eyeseetea/malariacare/domain/exception/push/PushDhisException.java
> Added dhis push error treatment

- app/src/cambodia/res/layout/sent_dashboard_filter.xml
> Make bigger dropdownlist

- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Utils.java
> added language selection list translation if some language is selected

- app/src/main/java/org/eyeseetea/malariacare/data/sync/exporter/ConvertToSDKVisitor.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/pushsummary/PushReport.java
- app/src/main/java/org/eyeseetea/malariacare/network/SurveyChecker.java
- app/src/test/java/org/eyeseetea/malariacare/data/sync/mappers/PushReportMapperTest.java
> Bug push quarantine bugs

- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java
- app/src/main/java/org/eyeseetea/malariacare/utils/Constants.java
> Not saving the warning values on the database

- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/push/PushUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/network/BanOrgUnitExecutor.java
- app/src/main/java/org/eyeseetea/malariacare/services/PushService.java
> Not pushing if lose connection and no checking banOrgUnit if you lose connection

- app/src/main/java/org/eyeseetea/malariacare/presentation/factory/monitor/utils/TimePeriodCalculator.java
> Showing current month values in the monitoring

- app/src/cambodia/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
- app/src/laos/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
- app/src/laos/res/raw/copyright.txt
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/myanmar/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
> Make copyright links work in laos

- app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java
- app/src/main/java/org/eyeseetea/malariacare/network/ServerAPIController.java
> Bug change timeout

- app/src/cambodia/res/values/donottranslate.xml
- app/src/laos/res/values/donottranslate.xml
> Change default server for cambodia and laos

- app/src/main/java/org/eyeseetea/malariacare/fragments/ReviewFragment.java
> Feature order review values using navigationcontroller

- app/src/main/java/org/eyeseetea/malariacare/fragments/ReviewFragment.java
> Fix review screen colors

- app/src/cambodia/java/org/eyeseetea/malariacare/strategies/SettingsActivityStrategy.java
- app/src/cambodia/res/xml/pref_general.xml
- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/SettingsActivityStrategy.java
- app/src/laos/java/org/eyeseetea/malariacare/strategies/SettingsActivityStrategy.java
- app/src/laos/res/xml/pref_general.xml
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/strategies/ASettingsActivityStrategy.java
- app/src/myanmar/java/org/eyeseetea/malariacare/strategies/SettingsActivityStrategy.java
> Feature hide url preference if developer option is not active

- app/src/cambodia/java/org/eyeseetea/malariacare/strategies/DashboardSentFilter.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/utils/PreferencesState.java
- app/src/main/java/org/eyeseetea/malariacare/layout/adapters/general/AddlArrayAdapter.java
> Fix dropdown list item size on sent filter

- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/ReviewFragmentStrategy.java
> Solved bug app closing when logout.

- app/src/ereferrals/java/org/eyeseetea/malariacare/domain/entity/InvalidLoginAttempts.java
- app/src/test/java/org/eyeseetea/malariacare/domain/entity/InvalidLoginAttemptsTest.java
> Bug invalid login attemps not working well

- app/src/main/java/org/eyeseetea/malariacare/LoginActivity.java
> Hide keyboard in loginActivity when ProgressBar is visible

- app/src/test/java/org/eyeseetea/malariacare/domain/entity/PregnantMonthNumberTest.java
> Feature pregnant month number unit test

- app/src/cambodia/java/org/eyeseetea/malariacare/data/database/datasources/ProgramLocalDataSource.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/data/database/ProgramLocalDataSource.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/data/database/datasources/ProgramLocalDataSource.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/data/sync/importer/strategies/PullControllerStrategy.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/SurveyFragmentStrategy.java
- app/src/laos/java/org/eyeseetea/malariacare/data/database/datasources/ProgramLocalDataSource.java
- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Program.java
- app/src/main/java/org/eyeseetea/malariacare/domain/boundary/repositories/IProgramRepository.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/GetUserProgramUIDUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/domain/usecase/push/MockedPushSurveysUseCase.java
- app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java
- app/src/myanmar/java/org/eyeseetea/malariacare/data/database/datasources/ProgramLocalDataSource.java
> Bug not showing ifoche surveys in unsent

- app/src/main/java/org/eyeseetea/malariacare/data/database/model/Survey.java
- app/src/main/java/org/eyeseetea/malariacare/presentation/factory/monitor/MonitorTableBuilder.java
> Solved bug showing survey question three times.

- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
> Solved bug crash when unregister receiver on BaseActivityStrategy

- app/src/ereferrals/assets/Questions.csv
- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
> Bug one invalid children not accept valid

- app/src/ereferrals/AndroidManifest.xml
- app/src/ereferrals/java/org/eyeseetea/malariacare/data/database/utils/REFDBProvider.java
> fix errerefals export db

- app/src/ereferrals/assets/Questions.csv
> set current method question not visible

- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/SettingsActivityStrategy.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/eyeseetea/malariacare/BaseActivity.java
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/java/org/eyeseetea/malariacare/strategies/ABaseActivityStrategy.java
- app/src/main/java/org/eyeseetea/malariacare/strategies/ASettingsActivityStrategy.java
> Bug not showing login when screen off

- app/src/ereferrals/assets/web_view_error/errorpage.html
- app/src/ereferrals/assets/web_view_error/errorpage_sw.html
- app/src/ereferrals/java/org/eyeseetea/malariacare/fragments/WebViewFragment.java
- app/src/ereferrals/res/values-sw/strings.xml
- app/src/ereferrals/res/values/donottranslate.xml
- app/src/ereferrals/res/values/strings.xml
> Bug wevview offline beahaviour

- app/src/ereferrals/java/org/eyeseetea/malariacare/data/database/CredentialsLocalDataSource.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/layout/utils/LayoutUtils.java
> Set the volunteer user on actionbar erreferals

- app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/YearSelectorQuestionView.java
- app/src/main/res/values/integer.xml
> set year interval as eReferrals website to 70 years

- app/src/ereferrals/java/org/eyeseetea/malariacare/data/sync/exporter/WSPushController.java
> validate connectivity before stars push process

- app/src/ereferrals/res/values-sw/strings.xml
- app/src/ereferrals/res/values/strings.xml
> Change volunteer in action bar  for ipc.

- app/src/ereferrals/res/layout/fragment_web_view.xml
> Change webview background

- app/src/ereferrals/java/org/eyeseetea/malariacare/data/sync/exporter/WSClient.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/data/sync/exporter/WSPushController.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
- app/src/ereferrals/res/values-sw/strings.xml
- app/src/ereferrals/res/values/strings.xml
> Add control illegallArgument webservice URL

- app/src/ereferrals/res/values-sw/strings.xml
- app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java
> Bug language translation lost when orientation changed

- app/src/test/java/org/eyeseetea/malariacare/common/FileReader.java
- app/src/test/java/org/eyeseetea/malariacare/common/PushReportCommon.java
- app/src/test/java/org/eyeseetea/malariacare/data/sync/mappers/PushReportMapperTest.java
- app/src/test/java/org/eyeseetea/malariacare/domain/entity/PushReportTest.java
- app/src/test/resources/import_summary_conflict_response.json
- app/src/test/resources/import_summary_data_values.json
- app/src/test/resources/import_summary_error_response.json
- app/src/test/resources/import_summary_success_response.json
> Feature refactor push report tests

- app/src/ereferrals/java/utils/PhoneMask.java
- app/src/testereferrals/java/org/eyeseetea/malariacare/domain/entitiy/PhoneTest.java
Closes #1302 
-Fixed length bug.
-Fixed bug in the function to replacing the prefix.
(00-00123456700 was converted as +-+1234567+)
-Added tests
> Bug fix ereferals phone mask

- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/SettingsActivityStrategy.java
- app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java
> disable logout when app go to background

- app/build.gradle
- app/src/ereferrals/res/values/strings.xml
- build.gradle
> evolve app version and change OFFLINE string by OFF LINE

- app/build.gradle
- app/src/cambodia/res/values/donottranslate.xml
- build.gradle
> Content change default server for cambodia

- app/src/laos/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
> Laos working with demo user, not checked sending survey to server.

- app/src/laos/java/org/eyeseetea/malariacare/strategies/BaseActivityStrategy.java
> Feature hide demo in developer

- app/src/laos/java/org/eyeseetea/malariacare/presentation/factory/monitor/rows/NegativeRowBuilder.java
- app/src/laos/java/org/eyeseetea/malariacare/presentation/factory/monitor/rows/PfRowBuilder.java
- app/src/laos/java/org/eyeseetea/malariacare/presentation/factory/monitor/rows/PositivityRateRowBuilder.java
- app/src/laos/res/values/donottranslate.xml
- app/src/myanmar/java/org/eyeseetea/malariacare/presentation/factory/monitor/rows/NegativeRowBuilder.java
- app/src/myanmar/java/org/eyeseetea/malariacare/presentation/factory/monitor/rows/PfRowBuilder.java
- app/src/myanmar/java/org/eyeseetea/malariacare/presentation/factory/monitor/rows/PositivityRateRowBuilder.java
- app/src/myanmar/java/org/eyeseetea/malariacare/views/question/singlequestion/DynamicStockImageRadioButtonSingleQuestionView.java
> fix monitoring missing strings in laos

- app/src/main/java/org/eyeseetea/malariacare/strategies/ALoginActivityStrategy.java
> use hideProgressBar instead of onFinishLoading for avoid animation bugs

- app/src/laos/res/values-lo/strings.xml
- app/src/main/res/layout/dynamic_tab_row_question_text.xml
> Bug layout problems in warnings for lao

- app/src/cambodia/java/org/eyeseetea/malariacare/strategies/ReviewFragmentStrategy.java
- app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/ReviewFragmentStrategy.java
- app/src/laos/java/org/eyeseetea/malariacare/strategies/ReviewFragmentStrategy.java
- app/src/main/java/org/eyeseetea/malariacare/domain/entity/Value.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/ReviewFragment.java
- app/src/myanmar/java/org/eyeseetea/malariacare/strategies/ReviewFragmentStrategy.java
> Display the option name instead of code in reviewscreen

- app/src/main/java/org/eyeseetea/malariacare/SplashScreenActivity.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/DashboardSentFragment.java
> Bug dashboard sent filter bug

- app/src/main/java/org/eyeseetea/malariacare/fragments/AVFragment.java
- app/src/main/java/org/eyeseetea/malariacare/fragments/ReviewFragment.java
- app/src/main/java/org/eyeseetea/malariacare/presentation/presenters/MediaPresenter.java
- app/src/main/java/org/eyeseetea/malariacare/presentation/presenters/ReviewPresenter.java
> Feature implement mvp on new av library tab

- app/build.gradle
- app/src/cambodia/res/xml/pref_general.xml
- app/src/ereferrals/res/xml/pref_general.xml
- app/src/laos/res/xml/pref_general.xml
- app/src/main/java/org/eyeseetea/malariacare/SettingsActivity.java
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/xml/pref_general.xml
- app/src/myanmar/res/xml/pref_general.xml
> Feature disable font customize in ereferals

- app/src/ereferrals/res/values-sw/strings.xml
- app/src/ereferrals/res/values/strings.xml
> Add terms from POEditor

- app/src/ereferrals/res/values-sw/strings.xml
- app/src/ereferrals/res/values/strings.xml
> fix duplicates in strings
